// Generated by Xata Codegen 0.30.0. Please do not edit.
import { buildClient } from '@xata.io/client';
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from '@xata.io/client';

const tables = [
  {
    name: 'products',
    checkConstraints: {
      products_xata_id_length_xata_id: {
        name: 'products_xata_id_length_xata_id',
        columns: ['xata_id'],
        definition: 'CHECK ((length(xata_id) < 256))',
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_products_xata_id_key: {
        name: '_pgroll_new_products_xata_id_key',
        columns: ['xata_id'],
      },
      products__pgroll_new_code_key: {
        name: 'products__pgroll_new_code_key',
        columns: ['code'],
      },
    },
    columns: [
      {
        name: 'code',
        type: 'text',
        notNull: true,
        unique: true,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'image',
        type: 'text',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'long_description',
        type: 'text',
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'order',
        type: 'int',
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'prev_price',
        type: 'int',
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'price',
        type: 'int',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'saving',
        type: 'int',
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'short_description',
        type: 'text',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'title',
        type: 'text',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'url',
        type: 'text',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'xata_createdat',
        type: 'datetime',
        notNull: true,
        unique: false,
        defaultValue: 'now()',
        comment: '',
      },
      {
        name: 'xata_id',
        type: 'text',
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: '',
      },
      {
        name: 'xata_updatedat',
        type: 'datetime',
        notNull: true,
        unique: false,
        defaultValue: 'now()',
        comment: '',
      },
      {
        name: 'xata_version',
        type: 'int',
        notNull: true,
        unique: false,
        defaultValue: '0',
        comment: '',
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Products = InferredTypes['products'];
export type ProductsRecord = Products & XataRecord;

export type DatabaseSchema = {
  products: ProductsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    'https://mrarchis3d-s-workspace-nd628j.us-east-1.xata.sh/db/4life-db',
  apiKey: import.meta.env.XATA_API_KEY,
  branch: import.meta.env.XATA_BRANCH,
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
